FYPMap/ViewModels/QuestionModalViewModel.cs
using System.Collections.Generic;
using System.Web;

namespace FYPMap.ViewModels
{
    public class QuestionModalViewModel
    {
        public QuestionModalViewModel(string question, List<string> answers, string correctAnswer, string placeId)
        {
            Question = question;
            Answers = answers;
            CorrectAnswer = correctAnswer;
            PlaceId = placeId;

            HttpContext.Current.Session["QuestionModalViewModel"] = this;
        }

        public QuestionModalViewModel() { }

        public string Question { get; set; }
        public List<string> Answers { get; set; }
        public string CorrectAnswer { get; set; }
        public string SelectedAnswer { get; set; }
        public string PlaceId { get; set; }
    }
}

FYPMap/Controllers/PlacesController.cs
using System;
using System.Linq;
using System.Web.Configuration;
using System.Web.Mvc;
using FYPMap.Interfaces;
using FYPMap.ViewModels;

namespace FYPMap.Controllers
{
    [Authorize]
    public class PlacesController : Controller
    {
        private readonly IPlaceDetailsHelper _placeDetailsHelper;
        private readonly IPlaceSearchHelper _placeSearchHelper;
        private readonly IQuestionHelper _questionHelper;
        private readonly ILeaderboardHelper _leaderboardHelper;

        public PlacesController(IPlaceDetailsHelper placeDetailsHelper, 
            IPlaceSearchHelper placeSearchHelper, IQuestionHelper questionHelper, ILeaderboardHelper leaderboardHelper)
        {
            _placeDetailsHelper = placeDetailsHelper;
            _placeSearchHelper = placeSearchHelper;
            _questionHelper = questionHelper;
            _leaderboardHelper = leaderboardHelper;
        }

        public ActionResult GetNearbyPlaces(string lat, string lng)
        {
            var nearbyRadius = Convert.ToInt32(WebConfigurationManager.AppSettings["NearbyRadius"]);
            var placesSearch = _placeSearchHelper.GetNearbyPlaces(lat, lng, nearbyRadius);
            var currentUserVisitedPlaces = _leaderboardHelper.GetCurrentUserVisitedPlaces();
            if (placesSearch.Status == "OK")
            {
                foreach (var place in currentUserVisitedPlaces)
                {
                    var placeInSearch = placesSearch.Result.FirstOrDefault(x => x.Place_id == place);
                    if (placeInSearch != null)
                        placeInSearch.Icon = "VISITED";
                }
                HttpContext.Session["NearbyPlaceNames"] = placesSearch.Result.Select(x => x.Name).ToList();
                return Json(new { results = placesSearch.Result}, JsonRequestBehavior.AllowGet);
            }

            return null;
        }

        public ActionResult GetImmediatePlaces(string lat, string lng)
        {
            var immediateRadius = Convert.ToInt32(WebConfigurationManager.AppSettings["ImmediateRadius"]);
            var placesSearch = _placeSearchHelper.GetNearbyPlaces(lat, lng, immediateRadius);
            var currentUserVisitedPlaces = _leaderboardHelper.GetCurrentUserVisitedPlaces();
            foreach (var place in currentUserVisitedPlaces)
            {
                var placeInSearch = placesSearch.Result.FirstOrDefault(x => x.Place_id == place);
                if (placeInSearch != null)
                    placesSearch.Result.Remove(placeInSearch);
            }

            if (placesSearch.Status == "OK" && placesSearch.Result.Count > 0)
            {
                var result = placesSearch.Result.First();
                var placeDetails = _placeDetailsHelper.GetPlaceDetails(result.Place_id).Result;
                var questionModalViewModel = _questionHelper.GetQuestion(placeDetails);
                return PartialView("_QuestionModal", questionModalViewModel);
            }

            return null;
        }

        public ActionResult SubmitModalQuestion(string selectedAnswer)
        {
            var questionModalViewModel = (QuestionModalViewModel)HttpContext.Session["QuestionModalViewModel"];
            if (selectedAnswer == questionModalViewModel.CorrectAnswer)
            {
                _leaderboardHelper.UpdateUserScore(questionModalViewModel.PlaceId);
                return Json(new { }, JsonRequestBehavior.AllowGet);
            }
            return null;
        }
    }
}

FYPMap/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FYP</title>
    <link rel="icon" href="@Url.Content("~/favicon.ico")">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-fixed-top navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FYP", "Map", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @{ if (User.Identity.IsAuthenticated)
                        {
                            <li><a href="@Url.Action("Map", "Home")"><span class="glyphicon glyphicon-play"></span> Game</a></li>
                            <li><a href="@Url.Action("Leaderboard", "Home")"><span class="glyphicon glyphicon-stats"></span> Leaderboard</a></li>
                            <li><a href="@Url.Action("Logout", "Home")"><span class="glyphicon glyphicon-log-out"></span> Logout (@User.Identity.Name)</a></li>
                        }
                        else
                        {
                            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"></span> Welcome Screen</a></li>
                            <li><a href="@Url.Action("Signup", "Home")"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                            <li><a href="@Url.Action("Login", "Home")"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>

                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - FYP</p>
        </footer>
    </div>
</body>
</html>

FYPMap/Views/Shared/_QuestionModal.cshtml
@using FYPMap.ViewModels
@model QuestionModalViewModel
@Scripts.Render("~/bundles/questionModal")
<!-- Modal content-->
<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title">Answer the following question correctly:</h4>
    </div>
    @using (Html.BeginForm("ModalQuestion", "Places", "FormMethod.Post"))
    {
        <div class="modal-body">
            <p>@Model.Question </p>
            @foreach (var answer in Model.Answers)
            {
                <label style="font-weight: normal;">
                    @Html.RadioButtonFor(a => a.SelectedAnswer, answer)
                    @answer
                </label><br />
            }
            <p class="text-danger wrongAnswerMessage"></p>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    }
</div>